version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rt_finance
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    environment:
      DATABASE_URL: "mysql://root:password@db:3306/rt_finance"
      JWT_SECRET: "sangat-rahasia"
      PORT: 5005
    ports:
      - "5005:5005"
    depends_on:
      - db

volumes:
  db_data:
